POST http://localhost:3000/api/user/create HTTP/1.1
Content-Type: application/json

{
  "firstname": "AJ",
  "lastname": "Starr",
  "age": 45,
  "password": "password123",
  "team": "developers",
  "email": "ajspeller"
}

###

PUT http://localhost:3000/api/user/update HTTP/1.1
Content-Type: application/json

{
  "_id": "5d22ac39ace82240bab5db65",
  "firstname": "AJ",
  "lastname": "Starr",
  "age": 25,
  "password": "password123",
  "team": "software engineers",
  "email": "ajspeller"
}

###

GET http://localhost:3000/api/user/retrieve HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3000/api/user/remove HTTP/1.1
Content-Type: application/json

{
  "_id": "5d22ac39ace82240bab5db65"
}
